### ISSUE TITLE
2.6 Design Manager Dashboard Page

### ISSUE THREAD

**Issue by Aweroes** [Kjkaikai/INF2001_P2-6#14]
## ToDo

- [ ] employee workload overview
- [ ] ferry schedule overview
- [ ] ferry status overview
