### ISSUE TITLE
2.8.2 Design IT Admin Crud Account Page

### ISSUE THREAD

**Issue by Aweroes** [Kjkaikai/INF2001_P2-6#6]
## ToDo

- [ ] create new employee acc
- [ ] create new manager acc
- [ ] modify employee acc
- [ ] modify manager acc
- [ ] delete employee acc
- [ ] delete manager acc
